# sfa deals with testing on_success, on_failure, always


# there are two types of error in powershell
# - terminating errors => exit ps session => example invalidCommand
# - non-terminating errors => does not exis ps session => example Write-Error "something"

jobs:
  - name: x86-64-windows-server-2016-host-sfa-on-success
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - dir
    on_success:
      - script: echo "this should be logged"

  - name: x86-64-windows-server-2016-host-sfa-on-failure
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"

  - name: x86-64-windows-server-2016-host-sfa-on-success-always
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - dir
    on_success:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"

  - name: x86-64-windows-server-2016-host-sfa-on-failure-always
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"

  - name: x86-64-windows-server-2016-host-sfa-on-success-error
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-error
          script:
            - dir
    on_success:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be success"

  - name: x86-64-windows-server-2016-host-sfa-on-failure-error
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-error
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"

  - name: x86-64-windows-server-2016-host-sfa-on-success-always-error
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-always-error
          script:
            - dir
    on_success:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be success"
    always:
      - script: echo "always begins and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "end of always"


  - name: x86-64-windows-server-2016-host-sfa-on-failure-always-error
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-always-error
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"
    always:
      - script: echo "always begins and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "end of always"

########### Tests Fail-ShippableBuild command in on_success, on_failure, always

  - name: x86-64-windows-server-2016-host-sfa-on-success-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - dir
    on_success:
      - script: echo "Build should fail and this should be logged"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-failure-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - invalidCommand
    on_failure:
      - script: echo "Build should fail and this should be logged"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-always-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - dir
    always:
      - script: echo "Build should fail and this should be logged"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-success-always-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - dir
    on_success:
      - script: echo "this should be logged"
    always:
      - script: echo "Build should fail and this should be logged"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-failure-always-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"
    always:
      - script: echo "Build should fail and this should be logged"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-success-error-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-error
          script:
            - dir
    on_success:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-failure-error-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-error
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"

  - name: x86-64-windows-server-2016-host-sfa-on-success-always-error-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-success-always-error
          script:
            - dir
    on_success:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"
    always:
      - script: echo "always begins and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "end of always"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"


  - name: x86-64-windows-server-2016-host-sfa-on-failure-always-error-sfa
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: on-failure-always-error
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be shown and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "build status should be failure"
      - script: Fail-ShippableBuild
      - script: echo "this line should not be shown"
    always:
      - script: echo "always begins and ErrorActionPreference = $ErrorActionPreference"
      - script: Write-Error "This is a non-terminating error"
      - script: invalidCommand
      - script: echo "this line is after a terminating error"
      - script: echo "end of always"

  - name: x86-64-windows-server-2016-host-sfa-on-success-time
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - echo "Sleeping for 10 seconds"
            - Start-Sleep -s 10
    on_success:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10

  - name: x86-64-windows-server-2016-host-sfa-on-failure-time
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - echo "Sleeping for 10 seconds"
            - Start-Sleep -s 10
            - invalidCommand
    on_failure:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10

  - name: x86-64-windows-server-2016-host-sfa-always-time
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - echo "Sleeping for 10 seconds"
            - Start-Sleep -s 10
            - dir
    always:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10

  - name: x86-64-windows-server-2016-host-sfa-on-success-always-time
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - echo "Sleeping for 10 seconds"
            - Start-Sleep -s 10
    on_success:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10
    always:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10

  - name: x86-64-windows-server-2016-host-sfa-on-failure-always-time
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: test-should-work
          script:
            - echo "Sleeping for 10 seconds"
            - Start-Sleep -s 10
            - invalidCommand
    on_failure:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10
    always:
      - script: echo "Sleeping for 10 seconds"
      - script: Start-Sleep -s 10
