jobs:
  - name: x86-64-ubuntu-14-04-dynamic-container-drydock-u14nodall
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: x8664u14dynamic
      container: true
    flags:
      - drydock
    steps:
      - TASK:
          name: check-node-4.8.7
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 4.8.7
            - test "$(node --version)" == "v4.8.7"
      - TASK:
          name: check-node-5.12.0
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 5.12.0
            - test "$(node --version)" == "v5.12.0"
      - TASK:
          name: check-node-6.11.5
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 6.11.5
            - test "$(node --version)" == "v6.11.5"
      - TASK:
          name: check-node-7.10.1
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 7.10.1
            - test "$(node --version)" == "v7.10.1"
      - TASK:
          name: check-node-8.9.4
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 8.9.4
            - test "$(node --version)" == "v8.9.4"
      - TASK:
          name: check-node-9.5.0
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 9.5.0
            - test "$(node --version)" == "v9.5.0"
      - TASK:
          name: use-not-built-in-version
          runtime:
            options:
              imageName: "drydock/u14nodall"
              imageTag: master
          script:
            - nvm use 9.4.0 || true
            - nvm install 9.4.0
            - nvm use 9.4.0
            - test "$(node --version)" == "v9.4.0"

  - name: x86-64-ubuntu-14-04-dynamic-container-drydock-u14phpall
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: x8664u14dynamic
      container: true
    flags:
      - drydock
    steps:
      - TASK:
          name: check-php-5.6
          runtime:
            options:
              imageName: "drydock/u14phpall"
              imageTag: master
          script:
            - eval "$(phpenv init -)"
            - /root/.phpenv/bin/phpenv global 5.6
            - php --version
      - TASK:
          name: check-php-7.0
          runtime:
            options:
              imageName: "drydock/u14phpall"
              imageTag: master
          script:
            - eval "$(phpenv init -)"
            - /root/.phpenv/bin/phpenv global 7.0
            - php --version
      - TASK:
          name: check-php-7.1
          runtime:
            options:
              imageName: "drydock/u14phpall"
              imageTag: master
          script:
            - eval "$(phpenv init -)"
            - /root/.phpenv/bin/phpenv global 7.1
            - php --version
