jobs:
  - name: x86-64-windows-server-2016-host-envs-single
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: world
          script:
            - gci env:*
            - if ( "$env:HELLO" -ne "world" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-single-break
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-pass-for-single-envs
          runtime:
            options:
              env:
                HELLO: "this contains a \"@ special character"
          script:
            - gci env:*

  - name: x86-64-windows-server-2016-host-envs-multiple
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-pass-for-multiple-envs
          runtime:
            options:
              env:
                HELLO: world
                HI: there
          script:
            - gci env:*
            - if ( "$env:HELLO" -ne "world" ) { Write-Error "incorrect env" }
            - if ( "$env:HI" -ne "there" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-inbuilt
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-have-inbuilt-envs
          script:
            - gci env:*
            - if ( "$env:SHIPPABLE_NODE_ARCHITECTURE" -ne "x86_64" ) { Write-Error "incorrect env" }
            - if ( "$env:SHIPPABLE_NODE_OPERATING_SYSTEM" -ne "WindowsServer_2016" ) { Write-Error "incorrect env" }
            - if ( "$env:TASK_NAME" -ne "should-have-inbuilt-envs" ) { Write-Error "incorrect env" }
            - if ( "$env:TASK_IN_CONTAINER" -ne "False" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-in-gitRepo
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: master-gitRepo
      - IN: gitlab-public-gitRepo
      - IN: bitbucket-public-gitRepo-3
      - TASK:
          name: should-have-gitRepo-envs
          script:
            - gci env:*
            # for github public repo
            - echo $env:MASTERGITREPO_PATH
            - cd $env:MASTERGITREPO_PATH\gitRepo
            - dir
            - cat README.md
            - if ( "$env:MASTERGITREPO_BRANCH" -ne "master" ) { Write-Error "incorrect env" }
            - if ( "$env:MASTERGITREPO_OPERATION" -ne "IN" ) { Write-Error "incorrect env" }
            # for gitlab public repo
            - echo $env:GITLABPUBLICGITREPO_PATH
            - cd $env:GITLABPUBLICGITREPO_PATH\gitRepo
            - dir
            - cat README.md
            - if ( "$env:GITLABPUBLICGITREPO_BRANCH" -ne "master" ) { Write-Error "incorrect env" }
            - if ( "$env:GITLABPUBLICGITREPO_OPERATION" -ne "IN" ) { Write-Error "incorrect env" }
            # for bitbucket public repo
            - echo $env:BITBUCKETPUBLICGITREPO3_PATH
            - cd $env:BITBUCKETPUBLICGITREPO3_PATH\gitRepo
            - dir
            - cat README.md
            - if ( "$env:BITBUCKETPUBLICGITREPO3_BRANCH" -ne "master" ) { Write-Error "incorrect env" }
            - if ( "$env:BITBUCKETPUBLICGITREPO3_OPERATION" -ne "IN" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-in-syncRepo
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: rc-cd_master
      - TASK:
          name: should-have-syncRepo-envs
          script:
            - gci env:*
            - $env:RCCD_MASTER_PATH = "$env:BUILD_DIR\IN\rc-cd_master\syncRepo"
            - echo $env:RCCD_MASTER_PATH
            - cd $env:RCCD_MASTER_PATH
            - dir
            - cat README.md

  - name: x86-64-windows-server-2016-host-envs-in-private-gitRepo
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: gitlab-private-gitRepo
      - IN: bitbucket-private-gitRepo
      # - IN: github-private-gitRepo-1
      - TASK:
          name: should-have-gitlab-private-gitRepo-envs
          script:
            - gci env:*
            - echo $env:GITLABPRIVATEGITREPO_PATH
            - cd $env:GITLABPRIVATEGITREPO_PATH\gitRepo
            - dir
            - cat README.md
            - if ( "$env:GITLABPRIVATEGITREPO_BRANCH" -ne "master" ) { Write-Error "incorrect env" }
            - if ( "$env:GITLABPRIVATEGITREPO_OPERATION" -ne "IN" ) { Write-Error "incorrect env" }
      - TASK:
          name: should-have-bitbucket-private-gitRepo-envs
          script:
            - gci env:*
            - echo $env:BITBUCKETPRIVATEGITREPO_PATH
            - cd $env:BITBUCKETPRIVATEGITREPO_PATH\gitRepo
            - dir
            - cat README.md
            - if ( "$env:BITBUCKETPRIVATEGITREPO_BRANCH" -ne "master" ) { Write-Error "incorrect env" }
            - if ( "$env:BITBUCKETPRIVATEGITREPO_OPERATION" -ne "IN" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-in-param
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: master-params
      - TASK:
          name: should-have-param-envs
          script:
            - gci env:*
            - if ( "$env:KEY1" -ne "value1" ) { Write-Error "incorrect env" }
            - if ( "$env:KEY2" -ne "value2" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-out-image
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - OUT: master-image-1
      - TASK:
          name: should-have-image-envs
          script:
            - gci env:*
            - if ( "$env:MASTERIMAGE1_NAME" -ne "master-image-1" ) { Write-Error "incorrect env" }
            # - Write-Output "versionName=master.$env:BUILD_NUMBER" | Out-File -Encoding utf8 -FilePath $env:JOB_STATE\master-image-1.env
            - cat $env:JOB_STATE\master-image-1.env
            - '"versionName=master.$env:BUILD_NUMBER" | Out-File -Encoding utf8 -FilePath $env:JOB_STATE\master-image-1.env -NoNewLine'

  - name: x86-64-windows-server-2016-host-envs-integration
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - IN: checking-do-integration
      - TASK:
          name: should-have-image-envs
          script:
            - gci env:*
            - if ( "$env:CHECKINGDOINTEGRATION_INTEGRATION_APITOKEN" -ne "not-really-an-api-token" ) { Write-Error "incorrect env" }

  - name: x86-64-windows-server-2016-host-envs-single-multiline
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-pass-for-multiline-envs
          runtime:
            options:
              env:
                HELLO: |
                  first line
                  second line
          script:
            - gci env:*
            - echo $env:HELLO

  - name: x86-64-windows-server-2016-host-envs-nested
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-envs
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-pass-for-nested-envs
          runtime:
            options:
              env:
                MYROOT: "/root"
                MYFILE: "$env:MYROOT/myfile.txt"
          script:
            - gci env:*
            - echo "$env:MYROOT"
            - echo "$env:MYFILE"
            - if ( "$env:MYROOT" -ne "/root" ) { Write-Error "incorrect env" }
            - if ( "$env:MYFILE" -ne "/root/myfile.txt" ) { Write-Error "incorrect env" }
