jobs:
  - name: x86-64-windows-server-2016-host-basic-single-valid
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-work
          script:
            - dir

  - name: x86-64-windows-server-2016-host-basic-single-invalid
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-not-work
          script:
            - invalidCommand

  - name: x86-64-windows-server-2016-host-basic-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-work
          script:
            - dir
            - echo "hello world"

  - name: x86-64-windows-server-2016-host-basic-multiple-invalid
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          script:
            - echo "next command will be invalid"
            - invalidCommand

  - name: x86-64-windows-server-2016-host-basic-multiple-error
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-not-work
          script:
            - echo "next command will throw error"
            - cat x
            - echo "this command should not even be executed"

  - name: x86-64-windows-server-2016-host-multitask-multiple-valid
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: say-hi
          script:
            - echo "hi 1"
            - echo "hi 2"
      - TASK:
          name: say-hello
          script:
            - echo "hello 1"
            - echo "hello 2"

  - name: x86-64-windows-server-2016-host-cancel
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: cancel-job-should-stop-task
          script:
            - dir
            - echo "hello world"
            - Start-Sleep -s 100
            - echo "This should not show up if job was cancelled 1"
            - echo "This should not show up if job was cancelled 2"
            - echo "This should not show up if job was cancelled 3"
            - echo "This should not show up if job was cancelled 4"
            - echo "This should not show up if job was cancelled 5"
            - echo "This should not show up if job was cancelled 6"
            - echo "This should not show up if job was cancelled 7"
            - echo "This should not show up if job was cancelled 8"
            - echo "This should not show up if job was cancelled 9"
            - echo "This should not show up if job was cancelled 10"
            - choco -h

#### Checking exit behaviour

  - name: x86-64-windows-server-2016-host-basic-exit-0-cmd
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-basic
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-exit
          script:
            - echo "next command will be exit"
            - exit 0
            - echo "this command should not be executed"
    on_success:
      - script: echo "This should be logged"
      - script: echo "and this too"
    on_failure:
      - script: echo "This should not be logged"

  - name: x86-64-windows-server-2016-host-basic-exit-1-cmd
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-basic
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-exit
          script:
            - echo "next command will be exit"
            - exit 1
            - echo "this command should not even be executed"
    on_success:
      - script: echo "This should not be logged"
    on_failure:
      - script: echo "This should be logged"

  - name: x86-64-windows-server-2016-host-basic-throw
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-windows-server-2016-host-basic
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: multiple-cmd-should-exit
          script:
            - echo "next command will be exit"
            - Throw "dummy error"
            - echo "this command should not even be executed"
    on_success:
      - script: echo "This should not be logged"
    on_failure:
      - script: echo "This should be logged"

########### Tests Fail-ShippableBuild command
  - name: x86-64-windows-server-2016-host-basic-fsb
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    flags:
      - x86-64
      - windows-server-2016
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: single-cmd-should-work
          script:
            - dir
            - Fail-ShippableBuild
            - echo "this should not be executed"
