# sfa deals with testing on_success, on_failure, always
jobs:
  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-success
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-show-on-success
          script:
            - ls
    on_success:
      - script: echo "this should be logged"

  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-failure
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-show-on-failure
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"

  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-success-always
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-show-on-success-always
          script:
            - ls
    on_success:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"

  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-failure-always
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-on-failure-always
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be logged"
    always:
      - script: echo "this is always script"

  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-success-invalid-command
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-show-on-success
          script:
            - ls
    on_success:
      - script: echo "this should be shown"
      - script: echo "value if ErrorActionPreference is $ErrorActionPreference"
      - script: invalidCommand
      - script: echo "this should be shown"
      - script: echo "build status should be success"

  - name: x86-64-ubuntu-14-04-dynamic-host-sfa-on-failure-invalid-command
    type: runSh
    runtime:
      architecture: x86_64
      nodePool: x8664u14dynamic
      container: false
    flags:
      - x86-64
      - windows-server-2016
      - x86-64-ubuntu-14-04-dynamic-host-sfa
    steps:
      - IN: x86-64-trigger
      - IN: windows-server-2016-trigger
      - TASK:
          name: should-show-on-failure-invalid-command
          script:
            - invalidCommand
    on_failure:
      - script: echo "this should be shown"
      - script: invalidCommand
      - script: echo "this should be shown"
      - script: echo "build status should be failure"
